### PR TITLE
Feature/flex direction

### PR DESCRIPTION
**Pull request by nbittich**
**Without flex direction:**

image

**With flex direction:**

image

### CODE REVIEW

**Review by aatauil — CHANGES_REQUESTED** [review]
Uhmm I actually think adding the following css rule is a more straightforward fix for this :p
```css
  au-c-alert__content {
  overflow: hidden;
  }
```
Since its already set to word-wrap: break-word we can just tell it not to go outside bounds

**Comment by nbittich** [comment]
> Uhmm I actually think adding the following css rule is a more straightforward fix for this :p
> 
> ```css
>   au-c-alert__content {
>   overflow: hidden;
>   }
> ```
> 
> Since its already set to word-wrap: break-word we can just tell it not to go outside bounds

it hides the message with the overflow hidden :( 
image

**Comment by mietcls** [comment]
https://appuniversum.github.io/appuniversum/utilities/break-word/ Could you try this?

**Comment by nbittich** [comment]
> https://appuniversum.github.io/appuniversum/utilities/break-word/ Could you try this?

It's the same issue. I think the problem is in the grid:

```html
      <li class="au-o-grid__item au-u-1-2 au-u-2-6@medium">
        {{#if this.model.error.message}}
        <AuAlert @alertIcon="cross" @alertTitle="Error" @alertskin={{"error"}}>
          <p class="au-word-wrap"> {{this.model.error.message}} </p>
        </AuAlert>
        {{/if}}
      </li>
```

If I change the classes of the li by just ` <li class="au-o-grid__item">` , it looks a bit better:

image

**Comment by aatauil** [comment]
The overflow-hidden actually fixes it for me and just breaks the word correctly. Maybe its a browser thing ?

**Comment by nbittich** [comment]
> The overflow-hidden actually fixes it for me and just breaks the word correctly. Maybe its a browser thing ?

maybe, which browser do you use?

**Pull request closed without merging**
